import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import styles from './page.module.css'
import { Providers } from "./providers";
import Counter from "./components/Counter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <nav className={styles.nav}>
            <Link className={styles.link} href='/auth'>Auth</Link>
            <Link className={styles.link} href='/users'>Users</Link>
            <Link className={styles.link} href='/products'>Products</Link>
            <Link className={styles.link} href='/cart'>Cart</Link>
            <Counter />
          </nav>
          {children}
        </Providers>
        
      </body>
    </html>
  );
}
